//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatHang
    {
        public int madon { get; set; }
        public Nullable<int> masp { get; set; }
        public Nullable<int> soluong { get; set; }
        public string size { get; set; }
        public Nullable<long> thanhtien { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
        public string ghichu { get; set; }
        public string diachi { get; set; }

        public DatHang(int madon, int? masp, int? soluong, string size, 
            long? thanhtien, DateTime? ngaydat, string ghichu, string diachi)
        {
            this.madon = madon;
            this.masp = masp;
            this.soluong = soluong;
            this.size = size;
            this.thanhtien = thanhtien;
            this.ngaydat = ngaydat;
            this.ghichu = ghichu;
            this.diachi = diachi;
        }

        public DatHang(int? masp, int? soluong, string size,
            long? thanhtien, DateTime? ngaydat, string ghichu, string diachi)
        {
            this.masp = masp;
            this.soluong = soluong;
            this.size = size;
            this.thanhtien = thanhtien;
            this.ngaydat = ngaydat;
            this.ghichu = ghichu;
            this.diachi = diachi;
        }

        public DatHang()
        {
        }
    }
}
