//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        public int masp { get; set; }
        public string tensp { get; set; }
        public string loaisanpham { get; set; }
        public Nullable<long> giasp { get; set; }
        public string mota { get; set; }
        public string anh { get; set; }
        public Nullable<int> luotxem { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
        public string kichco { get; set; }

        public Sanpham(int masp, string tensp, string loaisanpham, long? giasp,
            string mota, string anh, int? luotxem, DateTime? ngaydang, string kichco)
        {
            this.masp = masp;
            this.tensp = tensp;
            this.loaisanpham = loaisanpham;
            this.giasp = giasp;
            this.mota = mota;
            this.anh = anh;
            this.luotxem = luotxem;
            this.ngaydang = ngaydang;
            this.kichco = kichco;
        }

        public Sanpham(string tensp, string loaisanpham, long? giasp, string mota,
            string anh, int? luotxem, DateTime? ngaydang, string kichco)
        {
            this.tensp = tensp;
            this.loaisanpham = loaisanpham;
            this.giasp = giasp;
            this.mota = mota;
            this.anh = anh;
            this.luotxem = luotxem;
            this.ngaydang = ngaydang;
            this.kichco = kichco;
        }

        public Sanpham()
        {
        }
    }
}
