//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int matv { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public int age { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }

        public User(int matv, string username, string password, 
            string fullname, int age, string phone, string email, string address)
        {
            this.matv = matv;
            this.username = username;
            this.password = password;
            this.fullname = fullname;
            this.age = age;
            this.phone = phone;
            this.email = email;
            this.address = address;
        }

        public User()
        {
        }

        public User(string username, string password, string fullname,
            int age, string phone, string email, string address)
        {
            this.username = username;
            this.password = password;
            this.fullname = fullname;
            this.age = age;
            this.phone = phone;
            this.email = email;
            this.address = address;
        }
    }
}
